# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug"

callbacks: null

extras:
  ignore_warnings: False
  enforce_tags: False

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

trainer:
  max_epochs: 1
  accelerator: cpu # debuggers don't like gpus
  devices: 1 # debuggers don't like multiprocessing
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

data:
  batch_size: 32
  max_seq_len: 10

model:
  embed_dim: 36
  model:
    num_global_tokens: 8
    num_nonseq_tokens: 10
    num_blocks: 2
    ffn_hidden_dim: 48
    num_heads: 2
    num_seq: 3
    drop_out: 0.1

    semantic_groups_fn:
      mode: null

    kv_encoder:
      num_layers: 2
      ffn_hidden_ratio: 2.0
      drop_out: 0.1
      pos_bias_type: "rope"
      rel_pos_buckets: 32
      use_time_embedding: true
      num_time_buckets: 32
      time_bucket_fn: "log"

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0005
    betas: [ 0.9, 0.95 ]
    eps: 1e-8
    weight_decay: 0.01

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    _partial_: true
    T_0: 5
    T_mult: 2
    eta_min: 1e-6
